name: Timed Python Script Workflow

on:
  # Trigger the workflow on push to main branch
  push:
    branches: [ main, master ]
  
  # Allow manual triggering of the workflow
  workflow_dispatch:

# Set permissions
permissions:
  contents: read
  actions: write

jobs:
  run-timed-script:
    runs-on: ubuntu-latest
    
    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v4
    
    # Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    # Install any dependencies (if needed)
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Add any additional pip install commands here if you have dependencies
    
    # Run the Python script
    - name: Run timed script
      run: python script.py
      
    # Optional: Upload logs as artifact
    - name: Upload logs
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: script-logs
        path: |
          *.log
        retention-days: 5
